pm/apps/projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projects_list, name='projects_list'),
    path('project_detail/<int:pk>/', views.project_detail, name='project_detail'),
    path('project_create', views.project_create, name='project_create')
]

pm/pm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.projects.urls')),
    path('users/', include('apps.users.urls'))
]

pm/apps/projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Projects(models.Model):
    status_choices = [
        ('A', 'в процессе'),
        ('C', 'закрыт'),
        ('F', 'приостановлен')
    ]

    name = models.CharField(max_length=30)
    description = models.TextField()
    start = models.DateField()
    end = models.DateField()

    status = models.CharField(
        max_length=2,
        choices=status_choices,
        default='A'
    )
    manager = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='projects_manager',
    )

    class Meta:
        permissions = [
            ("manage_project", "Возможность управлять проектом")
        ]

    def __str__(self):
        return (f'Проект - {self.name}, дата начала - {self.start}, дата окончания - {self.end},\n'
                f'статус - {self.status}, менеджер проекта - {self.manager}')

pm/apps/tasks/models.py
from django.db import models
from ..projects.models import Projects
from django.contrib.auth.models import User

class Tasks(models.Model):
    priority_choices = [
        ('H', 'Высокий'),
        ('M', 'Средний'),
        ('L', 'Низкий')
    ]
    status_choices = [
        ('N', 'Не начато'),
        ('I', 'В процессе'),
        ('C', 'Завершено'),
    ]

    name = models.CharField(max_length=30)
    description = models.TextField()
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    priority = models.CharField(
        max_length=2,
        choices=priority_choices,
        default='H'
    )
    status = models.CharField(
        max_length=2,
        choices=status_choices,
        default='N'
    )
    start = models.DateField()
    end = models.DateField()
    '''
    в переменной ниже Tasks будет обращаться к определенному пользователю executor, 
    чтобы один пользователь мог назначаться испольнителем сразу нескольких задач.
    '''
    executor = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='tasks_executor',
                                 )

    class Meta:
        permissions = [
            ("view_assigned_task", "возможность просматривать задачу")
        ]

    def __str__(self):
        return (f'В проекте {self.project} задача - {self.name}, приоритет - {self.priority}, статус - {self.status},\n'
                f' начало - {self.start}, конец - {self.end}\n'
                f'исполнитель - {self.executor}')

pm/apps/projects/forms.py
from django import forms
from ..tasks.models import Tasks
from .models import Projects

class TaskForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ['name', 'priority', 'status', 'start', 'end', 'executor']

    start = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'class': 'form-control'
    }))
    end = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'class': 'form-control'
    }))

class Project_create_form(forms.ModelForm):
    class Meta:
        model = Projects
        fields = [
            'name',
            'description',
            'start',
            'end',
            'status',
            'manager'
        ]
    start = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'class': 'form-control'
    }))
    end = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'class': 'form-control'
    }))

pm/apps/projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from .models import Projects
from ..tasks.models import Tasks
from .forms import TaskForm, Project_create_form

# Create your views here.
def projects_list(request):
    projects = Projects.objects.all()
    user = request.user
    #user_tasks = Tasks.objects.filter(executor=request.user)
    is_admin = user.groups.filter(name='admin').exists()
    is_manager = user.groups.filter(name='manager').exists()
    is_executor = user.groups.filter(name='executor').exists()
    projects_manager = Projects.objects.filter(manager=user)
    projects_executor = Projects.objects.filter(tasks__executor=user).distinct()
    context = {
        'user': user,
        'is_admin': is_admin,
        'is_manager': is_manager,
        'is_executor': is_executor,
        'projects': projects,
        'projects_manager': projects_manager,
        'projects_executor': projects_executor,
    }
    return render(
        request,
        'projects/projects_list.html',
        context
    )

@login_required
def project_detail(request, pk):
    project = get_object_or_404(Projects, pk=pk)

    #if not (request.user == project.manager or request.user.is_superuser):
    #    return redirect('projects_list')

    tasks = Tasks.objects.filter(project=project)

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project
            task.save()
            return redirect('project_detail', pk=pk)
    else:
        form = TaskForm()

    user = request.user
    is_admin = user.groups.filter(name='admin').exists()
    is_manager = user.groups.filter(name='manager').exists()
    is_executor = user.groups.filter(name='executor').exists()

    context = {
        'project': project,
        'tasks': tasks,
        'form': form,
        'is_admin': is_admin,
        'is_manager': is_manager,
        'is_executor': is_executor,
    }

    return render(request, 'projects/project_detail.html', context)

@login_required
def project_create(request):
    users = User.objects.all()

    if request.method == 'POST':
        form = Project_create_form(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.save()
            return redirect('projects_list')
    else:
        form = Project_create_form()

    return render(request,'projects/project_create.html', {'form': form, 'users': users})

pm/apps/projects/templates/projects/project_create.html
{% extends 'pm/base.html' %}

{% block title %} Создание проекта {% endblock %}

{% block content %}
<div class="container mt-4">
  <h1 class="text-center">Создание нового проекта</h1>

  <form method="POST" class="mt-4">
    {% csrf_token %}
    <div class="mb-3">
      <label for="name" class="form-label">Название проекта</label>
      <input type="text" class="form-control" id="name" name="name" required>
    </div>

    <div class="mb-3">
      <label for="description" class="form-label">Описание проекта</label>
      <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
    </div>

    <div class="mb-3">
      <label for="start" class="form-label">Дата начала</label>
      <input type="date" class="form-control" id="start" name="start" required>
    </div>

    <div class="mb-3">
      <label for="end" class="form-label">Дата окончания</label>
      <input type="date" class="form-control" id="end" name="end" required>
    </div>

    <div class="mb-3">
      <label for="status" class="form-label">Статус проекта</label>
      <select class="form-select" id="status" name="status">
        <option value="A">В процессе</option>
        <option value="C">Закрыт</option>
        <option value="F">Приостановлен</option>
      </select>
    </div>

    <div class="mb-3">
      <label for="manager" class="form-label">Менеджер проекта</label>
      <select class="form-select" id="manager" name="manager">
        {% for user in users %}
          <option value="{{ user.id }}">{{ user.username }}</option>
        {% endfor %}
      </select>
    </div>

    <button type="submit" class="btn btn-success">Создать проект</button>
  </form>
</div>
{% endblock %}

pm/apps/projects/templates/projects/project_detail.html
{% extends 'pm/base.html' %}

{% block content %}
<div class="container">
    <h1>{{ project.name }}</h1>
    <p><strong>Описание:</strong> {{ project.description }}</p>
    <p><strong>Дата начала:</strong> {{ project.start }}</p>
    <p><strong>Дата окончания:</strong> {{ project.end }}</p>
    <p><strong>Статус:</strong> {{ project.get_status_display }}</p>
    <p><strong>Менеджер:</strong> {{ project.manager|default:"Не назначен" }}</p>

    <h2>Задачи проекта</h2>
    {% if project.tasks_set.all %}
        <table class="table">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Приоритет</th>
                    <th>Статус</th>
                    <th>Дата начала</th>
                    <th>Дата окончания</th>
                    <th>Исполнитель</th>
                </tr>
            </thead>
            <tbody>
                {% for task in project.tasks_set.all %}
                <tr>
                    <td>{{ task.name }}</td>
                    <td>{{ task.get_priority_display }}</td>
                    <td>{{ task.get_status_display }}</td>
                    <td>{{ task.start }}</td>
                    <td>{{ task.end }}</td>
                    <td>{{ task.executor|default:"Не назначен" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Задач пока нет.</p>
    {% endif %}

    <button id="toggleFormBtn" class="btn btn-primary">Добавить задачу</button>


    <div id="taskFormContainer" class="hidden mt-4">
        {% if is_admin or is_manager %}
        <h3>Добавить новую задачу</h3>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Добавить задачу</button>
            {% endif %}
        </form>
    </div>
</div>

{% block extra_js %}
    <script>
        const toggleButton = document.getElementById('toggleFormBtn');
        const formContainer = document.getElementById('taskFormContainer');

        toggleButton.addEventListener('click', function() {
            formContainer.classList.toggle('hidden');
        });
    </script>
{% endblock %}

{% block extra_css %}
    <style>
        .hidden {
            display: none;
        }

        #taskFormContainer {
            transition: all 0.3s ease-in-out;
        }


        #taskFormContainer.show {
            display: block;
        }
    </style>
{% endblock %}

{% endblock %}

pm/apps/projects/templates/projects/projects_list.html
{% extends 'pm/base.html' %}

{% block title %} Система управления проектами {% endblock %}

{% block content %}
<div class="container mt-4">
  <h1 class="text-center">ПРОЕКТЫ</h1>

<div class="text-center my-4">
    {% if is_admin %}
    <a href="{% url 'project_create' %}" class="btn btn-success">Создать проект</a>
    {% endif %}
  </div>

  <div class="row">
    {% if is_admin %}
    {% for project in projects %}
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ project.name }}</h5>
          <p class="card-text">{{ project.description|truncatechars:100 }}</p>
          <p class="card-text">
            <strong>Начало:</strong> {{ project.start }}<br>
            <strong>Конец:</strong> {{ project.end }}<br>
            <strong>Статус:</strong> {{ project.get_status_display }}<br>
            <strong>Менеджер</strong> {{ project.manager }}<br>
          </p>
          <a href="{% url 'project_detail' project.id %}" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    {% empty %}
      <p class="text-center">Нет проектов</p>
    {% endfor %}

    {% elif is_manager %}
    {% for project in projects_manager %}

    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ project.name }}</h5>
          <p class="card-text">{{ project.description|truncatechars:100 }}</p>
          <p class="card-text">
            <strong>Начало:</strong> {{ project.start }}<br>
            <strong>Конец:</strong> {{ project.end }}<br>
            <strong>Статус:</strong> {{ project.get_status_display }}<br>
            <strong>Менеджер</strong> {{ project.manager }}<br>
          </p>
          <a href="{% url 'project_detail' project.id %}" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    {% empty %}
      <p class="text-center">Нет проектов</p>
    {% endfor %}

    {% elif is_executor %}
    {% for project in projects_executor %}
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ project.name }}</h5>
          <p class="card-text">{{ project.description|truncatechars:100 }}</p>
          <p class="card-text">
            <strong>Начало:</strong> {{ project.start }}<br>
            <strong>Конец:</strong> {{ project.end }}<br>
            <strong>Статус:</strong> {{ project.get_status_display }}<br>
            <strong>Менеджер</strong> {{ project.manager }}<br>
          </p>
          <a href="{% url 'project_detail' project.id %}" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    {% empty %}
      <p class="text-center">Нет проектов</p>
    {% endfor %}

    {% else %}
    <p class="text-center">Нет проектов</p>
    {% endif %}
  </div>
</div>
{% endblock %}